// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: bank.sql

package db

import (
	"context"
	"database/sql"
)

const createBank = `-- name: CreateBank :one
INSERT INTO banks (
    swift_code,
    bank_name,
    bank_address,
    country_code,
    bank_type
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, swift_code, bank_name, bank_address, country_code, bank_type
`

type CreateBankParams struct {
	SwiftCode   string         `json:"swift_code"`
	BankName    string         `json:"bank_name"`
	BankAddress sql.NullString `json:"bank_address"`
	CountryCode string         `json:"country_code"`
	BankType    BankType       `json:"bank_type"`
}

func (q *Queries) CreateBank(ctx context.Context, arg CreateBankParams) (Bank, error) {
	row := q.db.QueryRowContext(ctx, createBank,
		arg.SwiftCode,
		arg.BankName,
		arg.BankAddress,
		arg.CountryCode,
		arg.BankType,
	)
	var i Bank
	err := row.Scan(
		&i.ID,
		&i.SwiftCode,
		&i.BankName,
		&i.BankAddress,
		&i.CountryCode,
		&i.BankType,
	)
	return i, err
}

const deleteBankBySwiftCode = `-- name: DeleteBankBySwiftCode :exec
DELETE FROM banks
WHERE $1 = swift_code
`

func (q *Queries) DeleteBankBySwiftCode(ctx context.Context, swiftCode string) error {
	_, err := q.db.ExecContext(ctx, deleteBankBySwiftCode, swiftCode)
	return err
}

const getBankBySwiftCode = `-- name: GetBankBySwiftCode :one
SELECT id, swift_code, bank_name, bank_address, country_code, bank_type FROM banks
WHERE swift_code = $1
`

func (q *Queries) GetBankBySwiftCode(ctx context.Context, swiftCode string) (Bank, error) {
	row := q.db.QueryRowContext(ctx, getBankBySwiftCode, swiftCode)
	var i Bank
	err := row.Scan(
		&i.ID,
		&i.SwiftCode,
		&i.BankName,
		&i.BankAddress,
		&i.CountryCode,
		&i.BankType,
	)
	return i, err
}

const getBanksByCountryISO2Code = `-- name: GetBanksByCountryISO2Code :many
SELECT id, swift_code, bank_name, bank_address, country_code, bank_type FROM banks
WHERE country_code = $1
`

func (q *Queries) GetBanksByCountryISO2Code(ctx context.Context, countryCode string) ([]Bank, error) {
	rows, err := q.db.QueryContext(ctx, getBanksByCountryISO2Code, countryCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bank
	for rows.Next() {
		var i Bank
		if err := rows.Scan(
			&i.ID,
			&i.SwiftCode,
			&i.BankName,
			&i.BankAddress,
			&i.CountryCode,
			&i.BankType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBanksBySwiftCodePrefix = `-- name: GetBanksBySwiftCodePrefix :many
SELECT id, swift_code, bank_name, bank_address, country_code, bank_type FROM banks
WHERE swift_code like $1
`

func (q *Queries) GetBanksBySwiftCodePrefix(ctx context.Context, swiftCode string) ([]Bank, error) {
	rows, err := q.db.QueryContext(ctx, getBanksBySwiftCodePrefix, swiftCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bank
	for rows.Next() {
		var i Bank
		if err := rows.Scan(
			&i.ID,
			&i.SwiftCode,
			&i.BankName,
			&i.BankAddress,
			&i.CountryCode,
			&i.BankType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
